language: python
sudo: false
branches:
only:
  - master
os:
  - linux
python:
  - 3.5
  - 3.6
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --add channels conda-forge --force
  - conda config --set channel_priority strict
  - conda create --yes -n TEST python=$TRAVIS_PYTHON_VERSION --file requirements.txt --file requirements-dev.txt
  - source activate TEST
  - pip install coveralls

install:
  - python setup.py install

script:
  - python setup.py sdist >/dev/null
  - python -m pytest -v tests/ --cov contextily

notifications:
    email:
        recipients:
            - daniel.arribas.bel@gmail.com
        on_failure: always

after_success:
    - coveralls
