language: python
sudo: false
branches:
only:
  - master
os:
  - linux
env:
  - PYTHON="3.5"
  - PYTHON="3.6"
  - PYTHON="3.7"
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --add channels conda-forge --force
  - conda create --yes -n TEST python=$PYTHON --file requirements.txt --file requirements-dev.txt
  - source activate TEST
  - pip install coveralls

install:
  - python -m pip install -e .
  - conda list

script:
  - python setup.py sdist >/dev/null
  - python -m pytest -v tests/ --cov contextily

notifications:
    email:
        recipients:
            - daniel.arribas.bel@gmail.com
        on_failure: always

after_success:
    - coveralls
